# versión de la API de kubernetes y el tipo de recurso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce

# especificaciones del deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: tukics/ecommerce:1.0.0
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30003
